spring.application.name=saysmile-backend

# Postgres Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/saysmile_db
spring.datasource.username=saysmile_admin
spring.datasource.password=saysmile_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6380

# LDAP Configuration (For Clinic Staff Auth)
spring.ldap.urls=ldap://localhost:389
spring.ldap.base=dc=saysmile,dc=local
spring.ldap.username=cn=admin,dc=saysmile,dc=local
spring.ldap.password=admin

# Server Config
server.port=8080
